services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank_sampah
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mock-ai:
    build: ./Mock-AI
    ports:
      - "8000:8000"
    volumes:
      - mock_ai_uploads:/app/mock-uploads

  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      NODE_ENV: production
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/bank_sampah?schema=public"
      JWT_SECRET: "ganti-dengan-random-secret-panjang"
      JWT_ACCESS_EXPIRES_IN: 1h
      JWT_REFRESH_SECRET: "ganti-dengan-random-refresh-secret-panjang"
      JWT_REFRESH_EXPIRES_IN: 30d
      AI_SERVICE_URL: "http://mock-ai:8000/predict"
      AI_SERVICE_TIMEOUT: 15000
    volumes:
      - backend_uploads:/app/src/uploads
    depends_on:
      postgres:
        condition: service_healthy
      mock-ai:
        condition: service_started

volumes:
  postgres_data:
  backend_uploads:
  mock_ai_uploads:
