services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Laravel12
      POSTGRES_DB: bank_sampah
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  waste-classifier:
    build: ./waste_classifier
    ports:
      - "8000:8000"

  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      NODE_ENV: production
      DATABASE_URL: "LINK DATABASE"
      JWT_SECRET: ""
      JWT_ACCESS_EXPIRES_IN: 1h
      JWT_REFRESH_SECRET: ""
      JWT_REFRESH_EXPIRES_IN: 30d
      AI_SERVICE_URL: "http://waste-classifier:8000/predict"
      AI_SERVICE_TIMEOUT: 15000
    volumes:
      - backend_uploads:/app/src/uploads
    depends_on:
      postgres:
        condition: service_healthy
      waste-classifier:
        condition: service_started

  db-seeder:
    image: postgres:16-alpine
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGHOST: postgres
      PGPORT: "5432"
      PGUSER: postgres
      PGPASSWORD: Laravel12
      PGDATABASE: bank_sampah
    volumes:
      - ./db-init:/seed
    entrypoint: ["sh", "/seed/seed.sh"]

volumes:
  postgres_data:
  backend_uploads:
